### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by SrihariThalla** [mapbox/wikimama#12]
Error:

```shell
$ node batch-match.js --file input.csv
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (/private/var/www/github/wikimama/batch-match.js:92:31)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:513:12)
```

`input.csv`:
```shell
Hyderabad,17.3616227,78.4747305,Q1361,25,30
```

Thanks!

**Comment by amishas157** [comment]
Hi @SrihariThalla , thanks for flagging this issue. This looks like the bbox for overpass query was set wrongly. Pushed this commit https://github.com/mapbox/wikimama/commit/1c30e7bd5c890327ef850336e6d77a74c68a9b6d which resolves the issue.

Let me know if the problem still persists. Thanks : )

**Comment by SrihariThalla** [comment]
Thanks, @amishas157 I'll try it out and will let you know if there is any problem!
